INSERT INTO DietRestrictions (name) VALUES ('Alcohol-Cocktail');
INSERT INTO DietRestrictions (name) VALUES ('Alcohol-Free');
INSERT INTO DietRestrictions (name) VALUES ('Celery-Free');
INSERT INTO DietRestrictions (name) VALUES ('Crustacean-Free');
INSERT INTO DietRestrictions (name) VALUES ('Dairy-Free');
INSERT INTO DietRestrictions (name) VALUES ('DASH');
INSERT INTO DietRestrictions (name) VALUES ('Egg-Free');
INSERT INTO DietRestrictions (name) VALUES ('Fish-Free');
INSERT INTO DietRestrictions (name) VALUES ('FODMAP-Free');
INSERT INTO DietRestrictions (name) VALUES ('Gluten-Free');
INSERT INTO DietRestrictions (name) VALUES ('Immuno-Supportive');
INSERT INTO DietRestrictions (name) VALUES ('Keto-Friendly');
INSERT INTO DietRestrictions (name) VALUES ('Kidney-Friendly');
INSERT INTO DietRestrictions (name) VALUES ('Kosher');
INSERT INTO DietRestrictions (name) VALUES ('Low Potassium');
INSERT INTO DietRestrictions (name) VALUES ('Low Sugar');
INSERT INTO DietRestrictions (name) VALUES ('Lupine-Free');
INSERT INTO DietRestrictions (name) VALUES ('Mediterranean');
INSERT INTO DietRestrictions (name) VALUES ('Mollusk-Free');
INSERT INTO DietRestrictions (name) VALUES ('Mustard-Free');
INSERT INTO DietRestrictions (name) VALUES ('No Oil Added');
INSERT INTO DietRestrictions (name) VALUES ('Paleo');
INSERT INTO DietRestrictions (name) VALUES ('Peanut-Free');
INSERT INTO DietRestrictions (name) VALUES ('Pecatarian');
INSERT INTO DietRestrictions (name) VALUES ('Pork-Free');
INSERT INTO DietRestrictions (name) VALUES ('Red-Meat-Free');
INSERT INTO DietRestrictions (name) VALUES ('Sesame-Free');
INSERT INTO DietRestrictions (name) VALUES ('Shellfish-Free');
INSERT INTO DietRestrictions (name) VALUES ('Soy-Free');
INSERT INTO DietRestrictions (name) VALUES ('Sugar-Conscious');
INSERT INTO DietRestrictions (name) VALUES ('Sulfite-Free');
INSERT INTO DietRestrictions (name) VALUES ('Tree-Nut-Free');
INSERT INTO DietRestrictions (name) VALUES ('Vegan');
INSERT INTO DietRestrictions (name) VALUES ('Vegetarian');
INSERT INTO DietRestrictions (name) VALUES ('Wheat-Free');
